// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

import (
	"github.com/ichi-2049/filmie-server/types"
)

type Movie struct {
	MovieID          int        `json:"movieID"`
	Title            string     `json:"title"`
	Overview         string     `json:"overview"`
	ReleaseDate      types.Date `json:"releaseDate"`
	ImageURL         string     `json:"imageUrl"`
	Popularity       float64    `json:"popularity"`
	OriginalLanguage string     `json:"originalLanguage"`
	VoteAverage      float64    `json:"voteAverage"`
	VoteCount        int        `json:"voteCount"`
}

type Query struct {
}

type User struct {
	UID   string `json:"uid"`
	Name  string `json:"name"`
	Email string `json:"email"`
}
