package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"

	graph "github.com/ichi-2049/filmie-server/graphql"
	gqlmodel "github.com/ichi-2049/filmie-server/graphql/models"
	"github.com/ichi-2049/filmie-server/graphql/resolver/converter"
)

// Movies is the resolver for the movies field.
func (r *queryResolver) Movies(ctx context.Context, input *gqlmodel.MovieConnectionInput) (*gqlmodel.MovieConnection, error) {
	movieConnection, err := r.container.GetMovieService().GetMovieConnection(input.First, input.After, input.Title)
	if err != nil {
		return nil, err
	}

	return converter.ConvertMovieConnection(movieConnection), nil
}

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
