package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"

	gqlmodel "github.com/ichi-2049/filmie-server/graphql/models"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, uid string) (*gqlmodel.User, error) {
	user, err := r.container.GetUserService().GetUser(uid)
	if err != nil {
		return nil, err
	}

	userModel := &gqlmodel.User{
		UID:   user.Uid,
		Name:  user.Name,
		Email: user.Email,
	}

	return userModel, nil
}
